export const MIG_R_WELD_AIR = {
    label: "",
    list: [ {
        name: "RF GRIP 15",
        image: "",
        co2: "180 A",
        gas: "150 A",
        pv: "60%",
        wire: "0.6 - 1.0 мм",
      },
      {
        name: "RF GRIP 25",
        image: "",
        co2: "250 A",
        gas: "200 A",
        pv: "60%",
        wire: "0.8 - 1.2 мм",
      },
      {
        name: "RF GRIP 26",
        image: "",
        co2: "315 A",
        gas: "250 A",
        pv: "60%",
        wire: "0.8 - 1.2 мм",
      },
      {
        name: "RF GRIP 36",
        image: "",
        co2: "360 A",
        gas: "320 A",
        pv: "60%",
        wire: "1.0 - 1.6 мм",
      },
      {
        name: "RF GRIP 36 LC",
        image: "",
        co2: "315 A",
        gas: "250 A",
        pv: "60%",
        wire: "0.8 - 1.6 мм",
      },
      {
        name: "RF GRIP 45",
        image: "",
        co2: "450 A",
        gas: "400 A",
        pv: "60%",
        wire: "1.0 - 2.4 мм",
      },],
  }
