export const MIG_RF_AIR = {
  label: "Ручные горелки RF GRIP",
  list: [
    {
      name: "RF GRIP 15",
      image: "",
      co2: "180 A",
      gas: "150 A",
      pv: "60%",
      wire: "0.6 - 1.0 мм",
    },
    {
      name: "RF GRIP 25",
      image: "",
      co2: "180 A",
      gas: "200 A",
      pv: "60%",
      wire: "0.6 - 1.0 мм",
    },
    {
      name: "RF GRIP 26",
      image: "",
      co2: "180 A",
      gas: "200 A",
      pv: "60%",
      wire: "0.6 - 1.0 мм",
    },
    {
      name: "RF GRIP 36",
      image: "",
      co2: "180 A",
      gas: "200 A",
      pv: "60%",
      wire: "0.6 - 1.0 мм",
    },
    {
      name: "RF GRIP 36 LC",
      image: "",
      co2: "180 A",
      gas: "200 A",
      pv: "60%",
      wire: "0.6 - 1.0 мм",
    },
    {
      name: "RF GRIP 45",
      image: "",
      co2: "180 A",
      gas: "200 A",
      pv: "60%",
      wire: "0.6 - 1.0 мм",
    },
  ],
}