export const BREADCRUMBS_DICTIONARY: Record<string, string> = {
  production: "Продукция",
  home: "Главная",
  blog: "Блог",
  documentation: 'Документация',
  contacts: 'Контакты',
  robotization: "Роботизация и автоматизация",
  chemistry: "Сварочная химия и аксессуары",
  quick_couplings: "Быстросъемные соединения",
  planers: "Строгачи",
  weld_chemistry: "Сварочная химия",
  carbon_electrodes: "Угольные электроды",
  electrical_holders: "Электродержатели DE2200 / DE2300 / DE2400 / DE2500",
  tungsten_electrodes: "Вольфрамовые электроды",
  bayonet_connectors: "Байонетные разъемы",
  other_accessories: "Прочие аксессуары",
  hand_torches: "Ручные горелки",
  equipment_and_other: "Оборудование и прочее",
  mig_rf_air: "Ручные горелки RF GRIP",
  "tig_r-weld_air": "Ручные горелки R-WELD",
  "tig_r-weld__liquid": "Ручные горелки R-WELD",
  mig_mb_air: "Ручные горелки MB EVO",
  "mig_r-weld_air": "Ручные горелки R-WELD",
  mig_mb_liquid: "Ручные горелки MB EVO",
  "mig_r-weld_liquid": "Ручные горелки R-WELD",
  welding_sources:"Сварочные источники",
  smoke_exhaust_systems: "Дымовытяжные установки",
  other: "Прочее",
};

