import { TDownloadsDB } from "./declarations"

export const DOWNLOADS_DB:TDownloadsDB = [
    {   id:0,
        label: 'Каталог 2023',
        path:'https://disk.yandex.ru/i/gi6DhbFwvmg24A',
    },
    {   id: 1,
        label: 'Каталог ROBO',
        path:'https://disk.yandex.ru/i/sGm5Y9Z3m819OQ',
    },
    {   id:2,
        label: 'Буклет робо-пакетов',
        path:'https://disk.yandex.ru/i/8UXoLoQ58VEd0A',
    },
    {   
        id:3,
        label: 'Паспорт безопасности ABIBLUE',
        path:'https://disk.yandex.ru/i/9ewVdRaptHiJCQ',
    },
    {   id:0,
        label: 'Каталог 2023',
        path:'https://disk.yandex.ru/i/gi6DhbFwvmg24A',
    },
    {   id: 1,
        label: 'Каталог ROBO',
        path:'https://disk.yandex.ru/i/sGm5Y9Z3m819OQ',
    },
    {   id:2,
        label: 'Буклет робо-пакетов',
        path:'https://disk.yandex.ru/i/8UXoLoQ58VEd0A',
    },
    {   
        id:3,
        label: 'Паспорт безопасности ABIBLUE',
        path:'https://disk.yandex.ru/i/9ewVdRaptHiJCQ',
    },
    {   id:0,
        label: 'Каталог 2023',
        path:'https://disk.yandex.ru/i/gi6DhbFwvmg24A',
    },
    {   id: 1,
        label: 'Каталог ROBO',
        path:'https://disk.yandex.ru/i/sGm5Y9Z3m819OQ',
    },
    {   id:2,
        label: 'Буклет робо-пакетов',
        path:'https://disk.yandex.ru/i/8UXoLoQ58VEd0A',
    },
    {   
        id:3,
        label: 'Паспорт безопасности ABIBLUE',
        path:'https://disk.yandex.ru/i/9ewVdRaptHiJCQ',
    },
]